### ISSUE TITLE
Login app not redirecting to home app landing page after selecting location

### ISSUE THREAD

**Issue by denniskigen** [openmrs/openmrs-esm-login#91]
![redirect-failure](https://user-images.githubusercontent.com/8509731/103513295-5d686a00-4e7b-11eb-9026-46dc8bdf2bd9.gif)

Steps to reproduce:
- Login
- Select a location
- Click `Confirm`

The login page is failing to successfully redirect the user to the home app landing page after selecting a location and clicking the `Confirm` button. Apologies if this is a known issue, just that it's been happening for quite some time now.

**Comment by FlorianRappl** [comment]
I think this is the failing login redirect.

It should be fixed by now.

**Comment by brandones** [comment]
Thanks Florian! Here's the commit: https://github.com/openmrs/openmrs-esm-login/commit/8abbb1179fa78f7c3a4e58823eb97845e2bbf9f9

**Comment by denniskigen** [comment]
Thank you!
